language: python
python:
- 3.6
- pypy3
matrix:
  include:
  - os: linux
    python: 3.7
    env: TOXENV=py37
    sudo: true
    dist: xenial
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: djcomlab
  password:
    secure: lH0OaO7H2UG13LlDixERMIurEMIOacVx1cEvjZ9sM8eNhCIJAJeZ6uN2dawWRNF4aFDmaH6VNoEEGOcsSfgki2NHV/fkzVEC4ex45zeYY7uF7vMnmsb3WOSkx8OPXlg6YS4lcQPinsApYPfbTgMc1KyI3UF/plz3AB+sThnxItp57tUEztfs7d5V25GF3vWp7NYtSIk3WCfoifxfh4uROEmba4L7j21eNKIfqK2mtGvzCHTnjciYYAs069AK40aDmMBSW8wHyW8mw1aSE8RY4XWKKJ7p2P0MEmzpKRz7Tce6fa9cykxdTJyOYIdSitlSQ9B+4TjWNvbec77tCyaLn4Fmh/mH65xM3mfF1p01Y/ov0p7TW1h8Jua44qc4Cjmfu6l7y1vbzpM6WodZsb+/qcyTXCezaTQnRAWE9/iVC7aAMamVo6OjzCgXXpg+JvbWbUOac9/jKeHMrHbMtAP5aF6yPrlkZDxHsDFV8xjqeDiKKigv59blBmxuWucC75rufNlqGJ1j5ZtDxaJaBn8HxS75KvE6T/FITtQ6jihwwgpjAc96EgwVexAYn51q5Sw1qad26OFVdCdmiMPPiTyboFzgS1FnJ1+UYkXfgjLzPSxXV5LX5r4A/pz7M94a144ce4b7GdMG554JKdHeVIWSmeTVQu5VGNBVZPSDhi60DhI=
  on:
    tags: true
    repo: djcomlab/textmining3
    python: 3.6
